# permissions for end users to edit avisyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: avisync-editor-role
rules:
- apiGroups:
  - hamlet.tanzu.vmware.com
  resources:
  - avisyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hamlet.tanzu.vmware.com
  resources:
  - avisyncs/status
  verbs:
  - get
