# permissions for end users to view avisyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: avisync-viewer-role
rules:
- apiGroups:
  - hamlet.tanzu.vmware.com
  resources:
  - avisyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hamlet.tanzu.vmware.com
  resources:
  - avisyncs/status
  verbs:
  - get
